# Generated by Django 4.2 on 2023-05-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_permissions_alter_user_role_alter_role_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='name',
        ),
        migrations.AddField(
            model_name='role',
            name='Role',
            field=models.CharField(choices=[('admin', 'ADMIN'), ('system_staff', 'SYSTEM_STAFF'), ('client_admin', 'CLIENT_ADMIN'), ('client_staff', 'CLIENT_STAFF')], default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='permissions',
            name='permission',
            field=models.CharField(max_length=500),
        ),
    ]
