# Generated by Django 4.2 on 2023-05-08 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_remove_role_name_role_role_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='Role',
            new_name='role',
        ),
    ]
