# Generated by Django 4.2 on 2023-05-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0005_rename_role_role_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='permission',
            field=models.TextField(max_length=500),
        ),
    ]
