# Generated by Django 4.2 on 2023-05-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0007_product_alter_finance_options_alter_role_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permissions',
            field=models.ManyToManyField(to='practice.permissions'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('system_staff', 'System_staff'), ('client_admin', 'CLIENT_ADMIN'), ('client_staff', 'CLIENT_STAFF'), ('client_premium_customer', 'CLIENT_PREMIUM_STAFF')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'ADMIN'), ('accountant', 'Accountant'), ('HR', 'HR'), ('client_admin', 'CLIENT_ADMIN'), ('client_staff', 'CLIENT_STAFF')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
