# Generated by Django 4.2 on 2023-05-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0009_alter_user_role_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='permission',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
